nodeLinker: node-modules
defaultSemverRangePrefix: ''
logFilters:
  - code: YN0086
    level: error
packageExtensions:
  '@typescript-eslint/project-service@*':
    peerDependenciesMeta:
      typescript:
        optional: true
