nodeLinker: node-modules
defaultSemverRangePrefix: ''
logFilters:
  - code: YN0086
    level: error
constraintsPath: ./constraints.pro
packageExtensions:
  '@typescript-eslint/project-service@*':
    peerDependenciesMeta:
      typescript:
        optional: true

catalog:
  '@emotion/react': '11.14.0'
  '@emotion/styled': '11.14.1'
  '@eslint/js': '9.36.0'
  '@fastify/multipart': '9.0.3'
  '@fastify/static': '8.2.0'
  '@fastify/swagger': '9.5.1'
  '@fastify/swagger-ui': '5.2.3'
  '@hookform/resolvers': '5.2.1'
  '@mui/icons-material': '7.3.5'
  '@mui/material': '7.3.5'
  '@tanstack/react-query': '5.84.2'
  '@types/audioworklet': '0.0.82'
  '@types/node': '24.2.1'
  '@types/react': '19.1.9'
  '@types/react-dom': '19.1.7'
  '@vitejs/plugin-react': '5.0.0'
  '@vitest/browser': '3.2.4'
  '@webgpu/types': '0.1.64'
  'axios': '1.12.2'
  'cpx2': '8.0.0'
  'date-fns': '4.1.0'
  'eslint': '9.36.0'
  'eslint-import-resolver-typescript': '4.4.4'
  'eslint-plugin-import-x': '4.16.1'
  'eslint-plugin-react': '7.37.5'
  'eslint-plugin-react-hooks': '5.2.0'
  'eslint-plugin-react-refresh': '0.4.22'
  'eslint-plugin-simple-import-sort': '12.1.1'
  'fastify': '5.4.0'
  'fastify-sse-v2': '4.2.1'
  'fastify-type-provider-zod': '6.0.0'
  'framer-motion': '12.23.12'
  'globals': '16.4.0'
  'grep-cli': '0.2.1'
  'i18next': '25.3.2'
  'i18next-parser': '9.3.0'
  'jiti': '2.6.0'
  'ncp': '2.0.0'
  'openapi-types': '12.1.3'
  'pino-pretty': '13.1.1'
  'playwright': '1.54.2'
  'prettier': '3.6.2'
  'react': '19.1.1'
  'react-dom': '19.1.1'
  'react-hook-form': '7.62.0'
  'react-i18next': '15.6.1'
  'selfsigned': '3.0.1'
  'tsx': '4.20.5'
  'typescript': '5.9.2'
  'typescript-eslint': '8.44.1'
  'vite': '7.1.1'
  'vite-plugin-mkcert': '1.17.8'
  'vitest': '3.2.4'
  'zod': '4.1.9'
  'zustand': '5.0.7'
