nodeLinker: node-modules
defaultSemverRangePrefix: ''
logFilters:
  - code: YN0086
    level: error
constraintsPath: ./constraints.pro
packageExtensions:
  '@typescript-eslint/project-service@*':
    peerDependenciesMeta:
      typescript:
        optional: true
