nodeLinker: node-modules
defaultSemverRangePrefix: ''
logFilters:
  - code: YN0086
    level: error
constraintsPath: ./constraints.pro
packageExtensions:
  '@typescript-eslint/project-service@*':
    peerDependenciesMeta:
      typescript:
        optional: true

catalog:
  '@emotion/react': '11.14.0'
  '@emotion/styled': '11.14.1'
  '@eslint/js': '9.36.0'
  '@fastify/multipart': '9.4.0'
  '@fastify/static': '9.0.0'
  '@fastify/swagger': '9.7.0'
  '@fastify/swagger-ui': '5.2.5'
  '@hookform/resolvers': '5.2.2'
  '@mui/icons-material': '7.3.8'
  '@mui/material': '7.3.8'
  '@tanstack/react-query': '5.90.21'
  '@types/audioworklet': '0.0.95'
  '@types/node': '25.2.3'
  '@types/react': '19.2.14'
  '@types/react-dom': '19.2.3'
  '@vitejs/plugin-react': '5.1.4'
  '@vitest/browser': '4.0.18'
  '@vitest/browser-playwright': '4.0.18'
  '@webgpu/types': '0.1.69'
  'axios': '1.13.5'
  'cpx2': '8.0.0'
  'date-fns': '4.1.0'
  'eslint': '9.36.0'
  'eslint-plugin-react': '7.37.5'
  'eslint-plugin-react-hooks': '7.0.1'
  'eslint-plugin-react-refresh': '0.5.0'
  'eslint-plugin-import-x': '4.16.1'
  'eslint-plugin-simple-import-sort': '12.1.1'
  'fastify': '5.7.4'
  'fastify-sse-v2': '4.2.2'
  'fastify-type-provider-zod': '6.1.0'
  'framer-motion': '12.34.0'
  'globals': '17.3.0'
  'grep-cli': '0.2.1'
  'i18next': '25.8.7'
  'i18next-parser': '9.3.0'
  'jiti': '2.6.1'
  'ncp': '2.0.0'
  'openapi-types': '12.1.3'
  'pino': '10.3.1'
  'pino-pretty': '13.1.3'
  'playwright': '1.58.2'
  'prettier': '3.8.1'
  'react': '19.2.4'
  'react-dom': '19.2.4'
  'react-hook-form': '7.71.1'
  'react-i18next': '16.5.4'
  'selfsigned': '5.5.0'
  'tsx': '4.21.0'
  'typescript': '5.9.3'
  'typescript-eslint': '8.55.0'
  'vite': '7.3.1'
  'vite-plugin-mkcert': '1.17.9'
  'vitest': '4.0.18'
  'zod': '4.3.6'
  'zustand': '5.0.11'
