[project]
name = "musetric-backend-workers"
version = "0.1.0"
description = "Musetric Backend Workers"
authors = [{ name = "Vladlen Popelenkov", email = "popelenkow@gmail.com" }]
requires-python = "==3.13.2"
dependencies = [
    "torch==2.8.0",
    "torchaudio==2.8.0",
    "rotary-embedding-torch==0.8.9",
    "einops==0.8.1",
    "numpy==2.2.6",
    "numba==0.61.2",
    "PyYAML==6.0.2",
]

[project.optional-dependencies]
cuda = [
    "torch==2.8.0",
    "torchaudio==2.8.0"
]

[dependency-groups]
check = [
    "black==25.1.0",
    "isort==6.0.1",
    "ruff==0.12.11"
]

[tool.uv]

[tool.uv.sources]
torch = [
  { index = "cuda-index", extra = "cuda" },
]
torchaudio = [
  { index = "cuda-index", extra = "cuda" },
]

[[tool.uv.index]]
name = "cuda-index"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/musetricBackendWorkers"]

[tool.black]
exclude = ".venv"

[tool.isort]
profile = "black"
skip = [".venv"]

[tool.ruff]
exclude = [".venv"]
lint.select = ["TID", "F"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"
