[project]
name = "musetric"
version = "0.1.0"
description = "Musetric Python Backend Application"
authors = [{ name = "Vladlen Popelenkov", email = "popelenkow@gmail.com" }]
readme = "readme.md"
requires-python = ">=3.13.2"
dependencies = [
    "fastapi[standard]==0.115.12"
]

[project.optional-dependencies]
dev = [
    "black==25.1.0",
    "isort==6.0.1",
    "ruff==0.11.10"
]

[tool.setuptools]
packages = ["musetric"]

[tool.isort]
metrics = "black"

[tool.ruff]
lint.select = ["TID"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"
