name: gh-pages
on:
  push:
    branches: [main]
    paths:
      - gh-pages/**
  pull_request:
    branches: [main]
    paths:
      - gh-pages/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gh-pages
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn
    - run: yarn build
    - run: yarn release
      if: ${{ github.event_name == 'push' }}
