name: musetric
on:
  push:
    branches: [main]
    paths:
      - musetric/**
      - musetric-api/**
  pull_request:
    branches: [main]
    paths:
      - musetric/**
      - musetric-api/**
  workflow_dispatch:
    inputs:
      npmPublishTag:
        type: choice
        description: 'npm publish tag'
        required: false
        options:
        - 
        - latest
        - beta
        - next
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./musetric
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - run: python ../.github/workflows/setBuildNumber.py
      env:
        npmPublishTag: ${{ github.event.inputs.npmPublishTag }}
        buildNumber: ${{ github.run_number }}
    - run: yarn
    - run: yarn lint
    - run: yarn build
    - run: yarn test
    - run: yarn perf
    - run: yarn publish --tag ${{ github.event.inputs.npmPublishTag }} --no-git-tag-version
      working-directory: ./musetric/dist
      if: github.event.inputs.npmPublishTag == 'next' || github.event.inputs.npmPublishTag == 'beta' || github.event.inputs.npmPublishTag == 'latest'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
