name: musetric-app
on:
  push:
    branches: [main]
    paths:
      - musetric-app/**
      - musetric/**
  pull_request:
    branches: [main]
    paths:
      - musetric-app/**
      - musetric/**
  workflow_dispatch:
    inputs:
      npmPublishTag:
        description: 'npm publish tag'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./musetric-app
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python ../.github/workflows/setBuildNumber.py
      env:
        npmPublishTag: ${{ github.event.inputs.npmPublishTag }}
        buildNumber: ${{ github.run_number }}
    - run: yarn
      name: yarn musetric
      working-directory: ./musetric
    - run: yarn
    - run: yarn lint
    - run: yarn build
    - run: yarn publish --tag ${{ github.event.inputs.npmPublishTag }} --no-git-tag-version
      working-directory: ./musetric-app/dist
      if: github.event.inputs.npmPublishTag == 'next' || github.event.inputs.npmPublishTag == 'beta' || github.event.inputs.npmPublishTag == 'latest'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
